---

####################################
# Default Config for Windows
####################################

# *** CHECK DEFAULT DIRECTORIES BEFORE RUNNING ***


# Backup type (Copy/Sync/Isolated)
backup_type: copy


# Max number of days to keep backups when using 'isolated' backup type 
# (zero for no limit)
max_isolation_days: 0


# Hidden files
ignore_hidden_files: true


# Specify root target directory for backup
target_dir: C:\Backups


# Add each source directory to backup...
source_dirs:
 - C:\Users\freedom35\Projects
 - C:\Users\freedom35\Documents\Specifications
 - "C:\Users\freedom35\Documents\Research & Development"


# Add any excluded directories
excluded_dirs:
 - obj
 - bin
 - _sgbak
 - ipch
 - .dropbox.cache
 - .vs


# Add extensions for excluded file types
excluded_types:
 - exe
 - dll
 - pdb
 - zip
 - scc
 - obj
 - sbr
 - ilk
 - pch
 - bsc
 - tlog
 - idb
 - lastbuildstate
 - manifest
 - cache
 - log
 - exp
 - tlh
 - tli
 - sdf
 - aps


...